// ─── Sample Data for Nimbus Gantt Demo ──────────────────────────────────────
// Realistic software delivery project data spanning 3 client groups, 50 tasks,
// 15 dependencies, and 8 team members.

import type { GanttTask, GanttDependency } from '@nimbus-gantt/core';

// ─── Helpers ────────────────────────────────────────────────────────────────

/** Return ISO date string offset from a base date by `days`. */
function d(base: Date, days: number): string {
  const ms = base.getTime() + days * 86_400_000;
  const dt = new Date(ms);
  return dt.toISOString().slice(0, 10);
}

// Today = 2026-04-01 — center the 4-month window around it.
// Window: 2026-02-01 → 2026-06-01
const TODAY = new Date(Date.UTC(2026, 3, 1)); // April 1, 2026

// ─── Sort-order counter ────────────────────────────────────────────────────
let seq = 0;
function nextSort(): number {
  return seq++;
}

// ─── Tasks ─────────────────────────────────────────────────────────────────

export const sampleTasks: GanttTask[] = [
  // ═══════════════════════════════════════════════════════════════════════════
  // Group 1: Acme Corp  (18 tasks)
  // ═══════════════════════════════════════════════════════════════════════════

  // ── Platform Migration (parent) ──
  {
    id: 'acme-pm',
    name: 'Platform Migration',
    startDate: d(TODAY, -45),
    endDate: d(TODAY, 25),
    status: 'Planning',
    groupId: 'acme',
    groupName: 'Acme Corp',
    sortOrder: nextSort(),
  },
  {
    id: 'acme-pm-db',
    name: 'Database Schema Design',
    startDate: d(TODAY, -45),
    endDate: d(TODAY, -20),
    progress: 0.8,
    status: 'Development',
    assignee: 'Alex Chen',
    parentId: 'acme-pm',
    groupId: 'acme',
    groupName: 'Acme Corp',
    sortOrder: nextSort(),
  },
  {
    id: 'acme-pm-api',
    name: 'API Gateway Setup',
    startDate: d(TODAY, -25),
    endDate: d(TODAY, 5),
    progress: 0.6,
    status: 'Development',
    assignee: 'Marcus Rodriguez',
    parentId: 'acme-pm',
    groupId: 'acme',
    groupName: 'Acme Corp',
    sortOrder: nextSort(),
  },
  {
    id: 'acme-pm-auth',
    name: 'Auth Service Migration',
    startDate: d(TODAY, -15),
    endDate: d(TODAY, 10),
    progress: 0.4,
    status: 'Testing',
    assignee: 'Sarah Kim',
    parentId: 'acme-pm',
    groupId: 'acme',
    groupName: 'Acme Corp',
    sortOrder: nextSort(),
    // Decorator demo: at-risk archetype — solid red border + RISK badge
    style: {
      borderStyle: 'solid',
      borderWidth: 2,
      borderColor: '#dc2626',
      badge: { text: 'RISK', placement: 'start', color: '#dc2626' },
      styleNote: 'Flagged as at-risk by host workflow',
    },
  },
  {
    id: 'acme-pm-data',
    name: 'Data Migration Scripts',
    startDate: d(TODAY, -5),
    endDate: d(TODAY, 20),
    progress: 0,
    status: 'Planning',
    assignee: 'Alex Chen',
    parentId: 'acme-pm',
    groupId: 'acme',
    groupName: 'Acme Corp',
    sortOrder: nextSort(),
  },
  {
    id: 'acme-pm-load',
    name: 'Load Testing',
    startDate: d(TODAY, 6),
    endDate: d(TODAY, 25),
    progress: 0,
    status: 'Planning',
    assignee: 'Priya Patel',
    parentId: 'acme-pm',
    groupId: 'acme',
    groupName: 'Acme Corp',
    sortOrder: nextSort(),
  },
  {
    id: 'acme-pm-docs',
    name: 'API Documentation',
    startDate: d(TODAY, 10),
    endDate: d(TODAY, 22),
    progress: 0,
    status: 'Planning',
    assignee: 'Lisa Chang',
    parentId: 'acme-pm',
    groupId: 'acme',
    groupName: 'Acme Corp',
    sortOrder: nextSort(),
  },

  // ── Mobile App v2 (parent) ──
  {
    id: 'acme-mob',
    name: 'Mobile App v2',
    startDate: d(TODAY, -40),
    endDate: d(TODAY, 35),
    status: 'Development',
    groupId: 'acme',
    groupName: 'Acme Corp',
    sortOrder: nextSort(),
  },
  {
    id: 'acme-mob-ui',
    name: 'UI Component Library',
    startDate: d(TODAY, -40),
    endDate: d(TODAY, -5),
    progress: 0.9,
    status: 'Development',
    assignee: 'Maya Tanaka',
    parentId: 'acme-mob',
    groupId: 'acme',
    groupName: 'Acme Corp',
    sortOrder: nextSort(),
  },
  {
    id: 'acme-mob-push',
    name: 'Push Notification Service',
    startDate: d(TODAY, -20),
    endDate: d(TODAY, 5),
    progress: 0.7,
    status: 'Testing',
    assignee: 'David Okonkwo',
    parentId: 'acme-mob',
    groupId: 'acme',
    groupName: 'Acme Corp',
    sortOrder: nextSort(),
  },
  {
    id: 'acme-mob-sync',
    name: 'Offline Sync Engine',
    startDate: d(TODAY, -10),
    endDate: d(TODAY, 20),
    progress: 0.3,
    status: 'Development',
    assignee: 'Marcus Rodriguez',
    parentId: 'acme-mob',
    groupId: 'acme',
    groupName: 'Acme Corp',
    sortOrder: nextSort(),
  },
  {
    id: 'acme-mob-perf',
    name: 'Performance Optimization',
    startDate: d(TODAY, 5),
    endDate: d(TODAY, 22),
    progress: 0.15,
    status: 'Development',
    assignee: 'Alex Chen',
    parentId: 'acme-mob',
    groupId: 'acme',
    groupName: 'Acme Corp',
    sortOrder: nextSort(),
  },
  {
    id: 'acme-mob-store',
    name: 'App Store Submission',
    startDate: d(TODAY, 30),
    endDate: d(TODAY, 30),
    progress: 0,
    status: 'Planning',
    isMilestone: true,
    parentId: 'acme-mob',
    groupId: 'acme',
    groupName: 'Acme Corp',
    sortOrder: nextSort(),
  },

  // ── DevOps Pipeline (parent) ──
  {
    id: 'acme-devops',
    name: 'DevOps Pipeline',
    startDate: d(TODAY, -55),
    endDate: d(TODAY, 15),
    status: 'Development',
    groupId: 'acme',
    groupName: 'Acme Corp',
    sortOrder: nextSort(),
  },
  {
    id: 'acme-devops-cicd',
    name: 'CI/CD Setup',
    startDate: d(TODAY, -55),
    endDate: d(TODAY, -30),
    progress: 1.0,
    status: 'Done',
    isCompleted: true,
    assignee: 'James Wilson',
    parentId: 'acme-devops',
    groupId: 'acme',
    groupName: 'Acme Corp',
    sortOrder: nextSort(),
    // Decorator demo: recently-completed archetype — dashed + muted + ✓
    style: {
      borderStyle: 'dashed',
      borderWidth: 2,
      fillStyle: 'muted',
      badge: { text: '✓', placement: 'end' },
      styleNote: 'Recently completed (last 7 days)',
    },
  },
  {
    id: 'acme-devops-monitor',
    name: 'Monitoring Dashboard',
    startDate: d(TODAY, -25),
    endDate: d(TODAY, 5),
    progress: 0.5,
    status: 'Development',
    assignee: 'James Wilson',
    parentId: 'acme-devops',
    groupId: 'acme',
    groupName: 'Acme Corp',
    sortOrder: nextSort(),
  },
  {
    id: 'acme-devops-alerts',
    name: 'Alerting Rules',
    startDate: d(TODAY, 0),
    endDate: d(TODAY, 15),
    progress: 0,
    status: 'Planning',
    assignee: 'Lisa Chang',
    parentId: 'acme-devops',
    groupId: 'acme',
    groupName: 'Acme Corp',
    sortOrder: nextSort(),
  },
  {
    id: 'acme-devops-security',
    name: 'Security Audit',
    startDate: d(TODAY, -10),
    endDate: d(TODAY, 8),
    progress: 0.35,
    status: 'Testing',
    assignee: 'David Okonkwo',
    parentId: 'acme-devops',
    groupId: 'acme',
    groupName: 'Acme Corp',
    sortOrder: nextSort(),
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // Group 2: TechStart Inc  (16 tasks)
  // ═══════════════════════════════════════════════════════════════════════════

  // ── E-Commerce Platform (parent) ──
  {
    id: 'ts-ecom',
    name: 'E-Commerce Platform',
    startDate: d(TODAY, -35),
    endDate: d(TODAY, 40),
    status: 'Development',
    groupId: 'techstart',
    groupName: 'TechStart Inc',
    sortOrder: nextSort(),
  },
  {
    id: 'ts-ecom-catalog',
    name: 'Product Catalog Service',
    startDate: d(TODAY, -35),
    endDate: d(TODAY, -5),
    progress: 0.85,
    status: 'Development',
    assignee: 'Priya Patel',
    parentId: 'ts-ecom',
    groupId: 'techstart',
    groupName: 'TechStart Inc',
    sortOrder: nextSort(),
  },
  {
    id: 'ts-ecom-cart',
    name: 'Shopping Cart',
    startDate: d(TODAY, -20),
    endDate: d(TODAY, 5),
    progress: 0.6,
    status: 'Testing',
    assignee: 'Maya Tanaka',
    parentId: 'ts-ecom',
    groupId: 'techstart',
    groupName: 'TechStart Inc',
    sortOrder: nextSort(),
  },
  {
    id: 'ts-ecom-payment',
    name: 'Payment Gateway Integration',
    startDate: d(TODAY, -5),
    endDate: d(TODAY, 20),
    progress: 0.4,
    status: 'Development',
    assignee: 'David Okonkwo',
    parentId: 'ts-ecom',
    groupId: 'techstart',
    groupName: 'TechStart Inc',
    sortOrder: nextSort(),
  },
  {
    id: 'ts-ecom-orders',
    name: 'Order Management System',
    startDate: d(TODAY, -10),
    endDate: d(TODAY, 25),
    progress: 0.1,
    status: 'Planning',
    assignee: 'Alex Chen',
    parentId: 'ts-ecom',
    groupId: 'techstart',
    groupName: 'TechStart Inc',
    sortOrder: nextSort(),
  },
  {
    id: 'ts-ecom-inventory',
    name: 'Inventory Sync',
    startDate: d(TODAY, 20),
    endDate: d(TODAY, 40),
    progress: 0,
    status: 'Planning',
    assignee: 'Lisa Chang',
    parentId: 'ts-ecom',
    groupId: 'techstart',
    groupName: 'TechStart Inc',
    sortOrder: nextSort(),
  },
  {
    id: 'ts-ecom-search',
    name: 'Search & Filtering',
    startDate: d(TODAY, -15),
    endDate: d(TODAY, 8),
    progress: 0.5,
    status: 'Development',
    assignee: 'Sarah Kim',
    parentId: 'ts-ecom',
    groupId: 'techstart',
    groupName: 'TechStart Inc',
    sortOrder: nextSort(),
  },

  // ── Analytics Dashboard (parent) ──
  {
    id: 'ts-analytics',
    name: 'Analytics Dashboard',
    startDate: d(TODAY, -30),
    endDate: d(TODAY, 30),
    status: 'Development',
    groupId: 'techstart',
    groupName: 'TechStart Inc',
    sortOrder: nextSort(),
  },
  {
    id: 'ts-analytics-pipe',
    name: 'Data Pipeline',
    startDate: d(TODAY, -30),
    endDate: d(TODAY, 0),
    progress: 0.7,
    status: 'Development',
    assignee: 'James Wilson',
    parentId: 'ts-analytics',
    groupId: 'techstart',
    groupName: 'TechStart Inc',
    sortOrder: nextSort(),
  },
  {
    id: 'ts-analytics-rt',
    name: 'Real-time Metrics',
    startDate: d(TODAY, -15),
    endDate: d(TODAY, 15),
    progress: 0.45,
    status: 'Development',
    assignee: 'Sarah Kim',
    parentId: 'ts-analytics',
    groupId: 'techstart',
    groupName: 'TechStart Inc',
    sortOrder: nextSort(),
  },
  {
    id: 'ts-analytics-reports',
    name: 'Custom Reports',
    startDate: d(TODAY, 5),
    endDate: d(TODAY, 25),
    progress: 0,
    status: 'Planning',
    assignee: 'Priya Patel',
    parentId: 'ts-analytics',
    groupId: 'techstart',
    groupName: 'TechStart Inc',
    sortOrder: nextSort(),
  },
  {
    id: 'ts-analytics-export',
    name: 'Export Engine',
    startDate: d(TODAY, 30),
    endDate: d(TODAY, 30),
    progress: 0,
    status: 'Planning',
    isMilestone: true,
    parentId: 'ts-analytics',
    groupId: 'techstart',
    groupName: 'TechStart Inc',
    sortOrder: nextSort(),
  },

  // ── Customer Portal (parent) ──
  {
    id: 'ts-portal',
    name: 'Customer Portal',
    startDate: d(TODAY, -50),
    endDate: d(TODAY, 20),
    status: 'Development',
    groupId: 'techstart',
    groupName: 'TechStart Inc',
    sortOrder: nextSort(),
  },
  {
    id: 'ts-portal-sso',
    name: 'SSO Integration',
    startDate: d(TODAY, -50),
    endDate: d(TODAY, -30),
    progress: 1.0,
    status: 'Done',
    isCompleted: true,
    assignee: 'Marcus Rodriguez',
    parentId: 'ts-portal',
    groupId: 'techstart',
    groupName: 'TechStart Inc',
    sortOrder: nextSort(),
    // Decorator demo: badge alone (no border / fill change)
    style: {
      badge: { text: '✓', placement: 'end' },
    },
  },
  {
    id: 'ts-portal-self',
    name: 'Self-Service Tools',
    startDate: d(TODAY, -20),
    endDate: d(TODAY, 10),
    progress: 0.55,
    status: 'Testing',
    assignee: 'Lisa Chang',
    parentId: 'ts-portal',
    groupId: 'techstart',
    groupName: 'TechStart Inc',
    sortOrder: nextSort(),
  },
  {
    id: 'ts-portal-kb',
    name: 'Knowledge Base',
    startDate: d(TODAY, -10),
    endDate: d(TODAY, 20),
    progress: 0.3,
    status: 'Development',
    assignee: 'Maya Tanaka',
    parentId: 'ts-portal',
    groupId: 'techstart',
    groupName: 'TechStart Inc',
    sortOrder: nextSort(),
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // Group 3: Global Financial  (16 tasks)
  // ═══════════════════════════════════════════════════════════════════════════

  // ── Compliance System (parent) ──
  {
    id: 'gf-compliance',
    name: 'Compliance System',
    startDate: d(TODAY, -40),
    endDate: d(TODAY, 30),
    status: 'Development',
    groupId: 'global-fin',
    groupName: 'Global Financial',
    sortOrder: nextSort(),
  },
  {
    id: 'gf-comp-kyc',
    name: 'KYC Verification',
    startDate: d(TODAY, -30),
    endDate: d(TODAY, 5),
    progress: 0.65,
    status: 'Testing',
    assignee: 'David Okonkwo',
    parentId: 'gf-compliance',
    groupId: 'global-fin',
    groupName: 'Global Financial',
    sortOrder: nextSort(),
    // Decorator demo: dotted border + colored NEW badge — third archetype
    style: {
      borderStyle: 'dotted',
      borderWidth: 2,
      borderColor: '#0ea5e9',
      badge: { text: 'NEW', placement: 'start', color: '#0ea5e9' },
    },
  },
  {
    id: 'gf-comp-aml',
    name: 'AML Screening',
    startDate: d(TODAY, -20),
    endDate: d(TODAY, 15),
    progress: 0.4,
    status: 'Development',
    assignee: 'Sarah Kim',
    parentId: 'gf-compliance',
    groupId: 'global-fin',
    groupName: 'Global Financial',
    sortOrder: nextSort(),
  },
  {
    id: 'gf-comp-reg',
    name: 'Regulatory Reporting',
    startDate: d(TODAY, 0),
    endDate: d(TODAY, 30),
    progress: 0.15,
    status: 'Planning',
    assignee: 'Priya Patel',
    parentId: 'gf-compliance',
    groupId: 'global-fin',
    groupName: 'Global Financial',
    sortOrder: nextSort(),
  },
  {
    id: 'gf-comp-audit',
    name: 'Audit Trail',
    startDate: d(TODAY, -25),
    endDate: d(TODAY, 10),
    progress: 0.5,
    status: 'Development',
    assignee: 'Alex Chen',
    parentId: 'gf-compliance',
    groupId: 'global-fin',
    groupName: 'Global Financial',
    sortOrder: nextSort(),
  },
  {
    id: 'gf-comp-sanctions',
    name: 'Sanctions Screening',
    startDate: d(TODAY, -10),
    endDate: d(TODAY, 18),
    progress: 0.25,
    status: 'Development',
    assignee: 'Marcus Rodriguez',
    parentId: 'gf-compliance',
    groupId: 'global-fin',
    groupName: 'Global Financial',
    sortOrder: nextSort(),
  },

  // ── Trading Platform (parent) ──
  {
    id: 'gf-trading',
    name: 'Trading Platform',
    startDate: d(TODAY, -40),
    endDate: d(TODAY, 45),
    status: 'Development',
    groupId: 'global-fin',
    groupName: 'Global Financial',
    sortOrder: nextSort(),
  },
  {
    id: 'gf-trade-feed',
    name: 'Market Data Feed',
    startDate: d(TODAY, -40),
    endDate: d(TODAY, -5),
    progress: 0.75,
    status: 'Development',
    assignee: 'James Wilson',
    parentId: 'gf-trading',
    groupId: 'global-fin',
    groupName: 'Global Financial',
    sortOrder: nextSort(),
  },
  {
    id: 'gf-trade-exec',
    name: 'Order Execution Engine',
    startDate: d(TODAY, -25),
    endDate: d(TODAY, 15),
    progress: 0.55,
    status: 'Development',
    assignee: 'Marcus Rodriguez',
    parentId: 'gf-trading',
    groupId: 'global-fin',
    groupName: 'Global Financial',
    sortOrder: nextSort(),
  },
  {
    id: 'gf-trade-risk',
    name: 'Risk Calculator',
    startDate: d(TODAY, -30),
    endDate: d(TODAY, 0),
    progress: 0.8,
    status: 'Testing',
    assignee: 'Priya Patel',
    parentId: 'gf-trading',
    groupId: 'global-fin',
    groupName: 'Global Financial',
    sortOrder: nextSort(),
  },
  {
    id: 'gf-trade-settle',
    name: 'Settlement Service',
    startDate: d(TODAY, 0),
    endDate: d(TODAY, 30),
    progress: 0.2,
    status: 'Planning',
    assignee: 'David Okonkwo',
    parentId: 'gf-trading',
    groupId: 'global-fin',
    groupName: 'Global Financial',
    sortOrder: nextSort(),
  },
  {
    id: 'gf-trade-recon',
    name: 'Reconciliation',
    startDate: d(TODAY, 25),
    endDate: d(TODAY, 45),
    progress: 0,
    status: 'Planning',
    assignee: 'Lisa Chang',
    parentId: 'gf-trading',
    groupId: 'global-fin',
    groupName: 'Global Financial',
    sortOrder: nextSort(),
  },

  // ── Client Onboarding (parent) ──
  {
    id: 'gf-onboard',
    name: 'Client Onboarding',
    startDate: d(TODAY, -50),
    endDate: d(TODAY, 20),
    status: 'Development',
    groupId: 'global-fin',
    groupName: 'Global Financial',
    sortOrder: nextSort(),
  },
  {
    id: 'gf-onboard-app',
    name: 'Digital Application',
    startDate: d(TODAY, -50),
    endDate: d(TODAY, -25),
    progress: 1.0,
    status: 'Done',
    isCompleted: true,
    assignee: 'Maya Tanaka',
    parentId: 'gf-onboard',
    groupId: 'global-fin',
    groupName: 'Global Financial',
    sortOrder: nextSort(),
  },
  {
    id: 'gf-onboard-doc',
    name: 'Document Verification',
    startDate: d(TODAY, -20),
    endDate: d(TODAY, 5),
    progress: 0.7,
    status: 'Testing',
    assignee: 'Sarah Kim',
    parentId: 'gf-onboard',
    groupId: 'global-fin',
    groupName: 'Global Financial',
    sortOrder: nextSort(),
  },
  {
    id: 'gf-onboard-prov',
    name: 'Account Provisioning',
    startDate: d(TODAY, -10),
    endDate: d(TODAY, 20),
    progress: 0.45,
    status: 'Development',
    assignee: 'James Wilson',
    parentId: 'gf-onboard',
    groupId: 'global-fin',
    groupName: 'Global Financial',
    sortOrder: nextSort(),
  },
];

// ─── Dependencies (15 finish-to-start) ─────────────────────────────────────

export const sampleDependencies: GanttDependency[] = [
  // Acme Corp: Platform Migration chain
  { id: 'dep-1', source: 'acme-pm-db', target: 'acme-pm-api', type: 'FS' },
  { id: 'dep-2', source: 'acme-pm-api', target: 'acme-pm-load', type: 'FS' },
  { id: 'dep-3', source: 'acme-pm-auth', target: 'acme-pm-data', type: 'FS' },

  // Acme Corp: Mobile App chain
  { id: 'dep-4', source: 'acme-mob-ui', target: 'acme-mob-sync', type: 'FS' },
  { id: 'dep-5', source: 'acme-mob-sync', target: 'acme-mob-store', type: 'FS' },

  // Acme Corp: DevOps chain
  { id: 'dep-6', source: 'acme-devops-cicd', target: 'acme-devops-monitor', type: 'FS' },

  // TechStart: E-Commerce chain
  { id: 'dep-7', source: 'ts-ecom-catalog', target: 'ts-ecom-cart', type: 'FS' },
  { id: 'dep-8', source: 'ts-ecom-cart', target: 'ts-ecom-payment', type: 'FS' },
  { id: 'dep-9', source: 'ts-ecom-orders', target: 'ts-ecom-inventory', type: 'FS' },

  // TechStart: Analytics chain
  { id: 'dep-10', source: 'ts-analytics-pipe', target: 'ts-analytics-rt', type: 'FS' },
  { id: 'dep-11', source: 'ts-analytics-reports', target: 'ts-analytics-export', type: 'FS' },

  // Global Financial: Compliance chain
  { id: 'dep-12', source: 'gf-comp-kyc', target: 'gf-comp-aml', type: 'FS' },

  // Global Financial: Trading chain
  { id: 'dep-13', source: 'gf-trade-feed', target: 'gf-trade-exec', type: 'FS' },
  { id: 'dep-14', source: 'gf-trade-risk', target: 'gf-trade-settle', type: 'FS' },

  // Cross-group: SSO Integration (TechStart) blocks Auth Service Migration (Acme)
  { id: 'dep-15', source: 'ts-portal-sso', target: 'acme-pm-auth', type: 'FS' },
];

// ─── Color Map ─────────────────────────────────────────────────────────────

export const sampleColorMap: Record<string, string> = {
  Planning: '#3b82f6',
  Development: '#22c55e',
  Testing: '#a855f7',
  UAT: '#14b8a6',
  Deployment: '#f97316',
  Done: '#6b7280',
};
